version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web:latest
    container_name: web
    hostname: web
    restart: always
    ports:
      - "8080:8080"